package com.dersler.kahvedunyasi.mernis;

//------------------------------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 8.0.1.1
//
// Created by Quasar Development 
//
// This class has been generated for test purposes only and cannot be used in any commercial project.
// To use it in commercial project, you need to generate this class again with Premium account.
// Check https://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.
//
// Licence: 31B44E7E757AB49A27409B5DE9A5C6F46DFD0FAA728E0EA6E0C440A2D6E73A557A9518F8D9E405AE34219811179E1473BA033252BC3339EDD2DBA795FA2D1B65
//------------------------------------------------------------------------
import java.util.Date;


public interface JAADateTimeConverter
{
    java.util.Date convertDateTime(String strDate);
    java.util.Date convertTime(String strDate);
    java.util.Date convertDate(String strDate);
    String convertDuration(String value);
    String getStringFromDateTime(Date value);
    String getStringFromDate(Date value);
    String getStringFromTime(Date value);
    String getStringFromDuration(String value);
}